# This file is a template, and might need editing before it works on your project.1
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: docker

services:
  - docker:dind

before_script:
  - sudo docker info
  - sudo docker-compose --version

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build:
  stage: build
  script:
    - echo "Do a build here"
    - sudo chmod +x ./bash/*
    - sudo ./bash/download-sonar-scanner.sh
    - sudo docker-compose down && sudo docker-compose up -d
    
test-sonarqube:
  stage: test
  script:
    - echo "Do a test here"
    #- sudo sonar-scanner 
    #- sudo rm -rf .scannerwork/

test-phpunit:
  stage: test
  script:
    - echo "Do another parallel test here"
    - echo "For example run a lint test"

deploy-testserver:
  stage: deploy
  script:
    - echo "Do your deploy here"

deploy-prodserver:
  stage: deploy
  script:
    - echo "Do your deploy here"
    - sed -i 's/Test/Production/g' ./html/application/views/login.php
  when: manual
