# Source from https://www.masterzendframework.com/docker-development-environment/
---
version: '2'

volumes:
  database_data:
    driver: local

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - mariadb
      - php      
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
  php:
    build: ./docker/php/
    expose:
      - 9000
    volumes:
      - ./html:/var/www/html
  mariadb:
    image: mariadb:10.4
    ports:
      - 3306:3306
    volumes:
      - ./docker/mariadb:/opt/data
    command: --init-file /opt/data/migration.sql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=neis0736_mut_2019
      - MYSQL_USER=lemp
      - MYSQL_PASSWORD=lemppassword
    restart: on-failure

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
      - php 
      - nginx
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    volumes:
     - ./sessions